### ISSUE TITLE
latest Webpack >= 4.x is breaking the project

### ISSUE THREAD

**Issue by sahilsk** [jscomplete/reactful#3]
The new webpack has "commonsChunkPlugin" removed and project assume all deps to be of latest version. Hence, the problem while starting the reactful app.

One fix is lowering the  webpack version but couldn't create a pull request :(

```
    "webpack": "^3.11.0",
```

```
PS C:\Users\someena\wkspace\phoenix> yarn start
yarn run v1.1.0
$ concurrently "yarn run webpack" "yarn run dev"
[0] C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:242
[0]                             throw err;
[0]                             ^
[0]
[0] Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
[0]     at Object.get [as CommonsChunkPlugin] (C:\Users\someena\wkspace\phoenix\node_modules\webpack\lib\webpack.js:165:10)
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\webpack.config.js:75:25)
[0]     at Module._compile (C:\Users\someena\wkspace\phoenix\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0]     at Function.Module._load (module.js:500:3)
[0]     at Module.require (module.js:568:17)
[0]     at require (C:\Users\someena\wkspace\phoenix\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[0]     at WEBPACK_OPTIONS (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:133:13)
[0]     at requireConfig (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:135:6)
[0]     at C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:142:17
[0]     at Array.forEach (<anonymous>)
[0]     at module.exports (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:140:15)
[0]     at yargs.parse (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:239:39)
[0]     at Object.parse (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
[0]     at C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:217:8
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:512:3)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0]     at Function.Module._load (module.js:500:3)
[0]     at Module.require (module.js:568:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\node_modules\webpack\bin\webpack.js:80:2)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
error Command failed with exit code 1.
PS C:\Users\someena\wkspace\phoenix> yarn start
yarn run v1.1.0
$ concurrently "yarn run webpack" "yarn run dev"
[0] C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:242
[0]                             throw err;
[0]                             ^
[0]
[0] Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
[0]     at Object.get [as CommonsChunkPlugin] (C:\Users\someena\wkspace\phoenix\node_modules\webpack\lib\webpack.js:165:10)
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\webpack.config.js:75:25)
[0]     at Module._compile (C:\Users\someena\wkspace\phoenix\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0]     at Function.Module._load (module.js:500:3)
[0]     at Module.require (module.js:568:17)
[0]     at require (C:\Users\someena\wkspace\phoenix\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[0]     at WEBPACK_OPTIONS (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:133:13)
[0]     at requireConfig (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:135:6)
[0]     at C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:142:17
[0]     at Array.forEach (<anonymous>)
[0]     at module.exports (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:140:15)
[0]     at yargs.parse (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:239:39)
[0]     at Object.parse (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
[0]     at C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:217:8
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:512:3)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0]     at Function.Module._load (module.js:500:3)
[0]     at Module.require (module.js:568:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\node_modules\webpack\bin\webpack.js:80:2)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
error Command failed with exit code 1.PS C:\Users\someena\wkspace\phoenix> yarn start
yarn run v1.1.0
$ concurrently "yarn run webpack" "yarn run dev"
[0] C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:242
[0]                             throw err;
[0]                             ^
[0]
[0] Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
[0]     at Object.get [as CommonsChunkPlugin] (C:\Users\someena\wkspace\phoenix\node_modules\webpack\lib\webpack.js:165:10)
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\webpack.config.js:75:25)
[0]     at Module._compile (C:\Users\someena\wkspace\phoenix\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0]     at Function.Module._load (module.js:500:3)
[0]     at Module.require (module.js:568:17)
[0]     at require (C:\Users\someena\wkspace\phoenix\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[0]     at WEBPACK_OPTIONS (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:133:13)
[0]     at requireConfig (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:135:6)
[0]     at C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:142:17
[0]     at Array.forEach (<anonymous>)
[0]     at module.exports (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:140:15)
[0]     at yargs.parse (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:239:39)
[0]     at Object.parse (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
[0]     at C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:217:8
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:512:3)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0]     at Function.Module._load (module.js:500:3)
[0]     at Module.require (module.js:568:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\node_modules\webpack\bin\webpack.js:80:2)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
error Command failed with exit code 1.PS C:\Users\someena\wkspace\phoenix> yarn start
yarn run v1.1.0
$ concurrently "yarn run webpack" "yarn run dev"
[0] C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:242
[0]                             throw err;
[0]                             ^
[0]
[0] Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
[0]     at Object.get [as CommonsChunkPlugin] (C:\Users\someena\wkspace\phoenix\node_modules\webpack\lib\webpack.js:165:10)
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\webpack.config.js:75:25)
[0]     at Module._compile (C:\Users\someena\wkspace\phoenix\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0]     at Function.Module._load (module.js:500:3)
[0]     at Module.require (module.js:568:17)
[0]     at require (C:\Users\someena\wkspace\phoenix\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[0]     at WEBPACK_OPTIONS (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:133:13)
[0]     at requireConfig (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:135:6)
[0]     at C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:142:17
[0]     at Array.forEach (<anonymous>)
[0]     at module.exports (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\convert-argv.js:140:15)
[0]     at yargs.parse (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:239:39)
[0]     at Object.parse (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
[0]     at C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:217:8
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\node_modules\webpack-cli\bin\webpack.js:512:3)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0]     at Function.Module._load (module.js:500:3)
[0]     at Module.require (module.js:568:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\someena\wkspace\phoenix\node_modules\webpack\bin\webpack.js:80:2)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
error Command failed with exit code 1.
```

**Comment by samerbuna** [comment]
This should be fixed with the release 0.5.3
